http.host: 0.0.0.0

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1

## OLD - Remove
#cluster.name: "docker-cluster"
#network.host: 0.0.0.0 
